export const params = {
  CONTROL_KEYS: ["ArrowDown","ArrowUp", "ArrowLeft", "ArrowRight", "KeyW", "KeyA", "KeyS", "KeyD", "Space"],
  STARS_COUNT: 100,
  CRASH_SOUND_INTERVAL: 10,
  CIRCLE_FULL_ANGLE: Math.PI * 2,

  PLAYER_IMAGE_WIDTH: 48,
  PLAYER_IMAGE_HEIGHT: 48,
  PLAYER_RADIUS: 24,
  PLAYER_SPEED: 5,
  PLAYER_ZERO_ANGLE: -Math.PI * 0.5,
  CROSSHAIR_CORRECTION: 10,

  SOUND_ENGINE_FADEOUT: 0.04,

  PROJECTILE_SPEED: 20,
  PROJECTILE_RADIUS: 3,
  PROJECTILE_COLOR: "white",

  ASTEROID_IMAGE_SIZE: 120,
  ASTEROID_FULLSIZE: 120,
  ASTEROID_HALFSIZE: 70,
  ASTEROID_MINSIZE: 40,
  ASTEROIDS_INTERVAL: 1000,
  ASTEROID_INITIAL_SPEED: 50,
  ASTEROID_SPEED_MULTIPLIER: 0.01,
  ASTEROID_SPEED_TO_SIZE_VARIABILITY: 10,
  ASTEROID_ROTATION_SPEED: 5,
  ASTEROID_SIZE_VARIABILITY: 0.1,
  DEBRIS_COUNT_FULLSIZE: 2,
  DEBRIS_COUNT_HALFSIZE: 3,

  PARTICLES_SIZE_RATIO: 0.015,
  PARTICLES_COUNT: 15,
  PARTICLES_BLINKAGE_MULT: 2,
  PARTICLES_FRICTION: 0.99,
  PARTICLES_FADEOUT: 0.01,

  SCORE_FULLSIZE: 1,
  SCORE_HALFSIZE: 2,
  SCORE_MINSIZE: 4,
  SCORE_FONT_SIZE: 40,

  FONT_COLOR: "white",
  TITLE_FONT: "pixelEmulator",
  MAIN_FONT: "pixelColeco",
  HUD_HORIZONTAL_OFFSET: 30,
  HUD_VERTICAL_FONT_OFFSET: 50,
  HUD_VERTICAL_ICON_OFFSET: 20,

  LIMIT_ASTEROIDS: 100,
  LIMIT_PARTICLES: 1000,

  EXPLOSION_IMAGE_SIZE: 94,
  MUTE_IMAGE_WIDTH: 317,
  MUTE_IMAGE_HEIGHT: 270,
  MUTE_ICON_WIDTH: 50,
};
